//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinteoDAL.EcashDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECashDbEntities : DbContext
    {
        public ECashDbEntities()
            : base("name=ECashDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_GetCatagories_Result> sp_GetCatagories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCatagories_Result>("sp_GetCatagories");
        }
    
        public virtual ObjectResult<sp_login_Result> sp_login(string mobileNo, string password)
        {
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_login_Result>("sp_login", mobileNoParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_Register(string username, string emailid, string mobileNo, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var emailidParameter = emailid != null ?
                new ObjectParameter("Emailid", emailid) :
                new ObjectParameter("Emailid", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_Register", usernameParameter, emailidParameter, mobileNoParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_GetVideoContent_Result> sp_GetVideoContent(Nullable<int> catagoryId)
        {
            var catagoryIdParameter = catagoryId.HasValue ?
                new ObjectParameter("CatagoryId", catagoryId) :
                new ObjectParameter("CatagoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetVideoContent_Result>("sp_GetVideoContent", catagoryIdParameter);
        }
    }
}
